apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: increase-vm-max-map-count
          image: alpine:latest
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: sonarqube
          image: sonarqube:community
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          resources:  # Добавьте этот блок
            requests:
              memory: "3Gi"
              cpu: "0.5"
            limits:
              memory: "4Gi"
              cpu: "1"
          ports:
            - containerPort: 9000
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"
            - name: SONARQUBE_WEB_JVMOPTS
              value: "-Xmx2048m -Xms1024m"
            - name: ES_JAVA_OPTS
              value: "-Xmx2g -Xms1g"
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonarqube-data
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data