name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- Backend ----------
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies (Backend)
        working-directory: backend
        run: npm install

      - name: Run Backend Tests
        working-directory: backend
        run: npm test -- --coverage
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      # ---------- Frontend ----------
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test -- --coverage
        
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            backend/coverage
            frontend/coverage

  sonarqube-scan:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: .

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=blog-app
            -Dsonar.sources=./backend/src,./frontend/src
            -Dsonar.tests=./backend/src,./frontend/src
            -Dsonar.test.inclusions=**/*.spec.js,**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
            -Dsonar.coverage.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js
            -Dsonar.qualitygate.wait=true

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [test, sonarqube-scan]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Build Backend Docker image
        run: docker build -t swerthk/blog-backend:latest ./backend

      - name: Build Frontend Docker image
        run: docker build -t swerthk/blog-frontend:latest ./frontend

      - name: Save Backend Docker image
        run: docker save swerthk/blog-backend:latest -o backend.tar

      - name: Save Frontend Docker image
        run: docker save swerthk/blog-frontend:latest -o frontend.tar

      - name: Upload Docker images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            backend.tar
            frontend.tar

  docker-push:
    name: Push Docker Images
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: .

      - name: Load Backend Docker image
        run: docker load -i backend.tar

      - name: Load Frontend Docker image
        run: docker load -i frontend.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker image
        run: docker push swerthk/blog-backend:latest

      - name: Push Frontend Docker image
        run: docker push swerthk/blog-frontend:latest

  deploy:
    needs: [sonarqube-scan, docker-push]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install YC CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authorize YC CLI
        run: |
          yc config set service-account-key <(echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY }}")
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Get cluster credentials
        run: yc managed-kubernetes cluster get-credentials cat813i6hpesg9o1qsdo --external

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/frontend/
          kubectl apply -f k8s/backend/
          kubectl apply -f k8s/sonarqube/

      - name: Restart deployments
        run: |
          kubectl rollout restart deployment blog-backend
          kubectl rollout restart deployment blog-frontend
