name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- Backend ----------
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies (Backend)
        working-directory: backend
        run: npm install

      - name: Run Backend Tests
        working-directory: backend
        run: npm test
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}

      # ---------- Frontend ----------
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test

  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test  # Запускается только если тесты успешны

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Сборка Frontend (если есть статическая сборка)
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      # Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker image
        run: |
          docker build -t swerthk/blog-backend:latest ./backend
          docker push swerthk/blog-backend:latest

      - name: Build and Push Frontend Docker image
        run: |
          docker build -t swerthk/blog-frontend:latest ./frontend
          docker push swerthk/blog-frontend:latest
